spring:
  datasource:
    url: jdbc:mysql://192.168.7.8:3306/asl_station?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ppts_test
    password: ppts_test

server:
  port: 2592
  servlet:
    context-path: /teamnote