spring:
  datasource:
    url: jdbc:mysql://192.168.3.81:3306/teamnote?characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    druid:
      # 初始化的连接数
      initial-size: 10
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接的最大等待时间，毫秒
      max-wait: 60000
      # 开启连接有效性检查，如果空闲时间大于 time-between-eviction-runs-millis 指定的时间，则使用 validation-query 进行检测
      test-while-idle: true
      # 允许的最大空闲时间，作为 test-while-idle 的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间的时间差，如果大于该值，则关闭连接
      min-evictable-idle-time-millis: 30000
      # 用于检测连接有效性的 SQL ，MySQL 使用 select 'x' ，Oracle 使用 select 1 from dual
      validation-query: select 'x'
      # 申请连接时不检测连接有效性，提高性能
      test-on-borrow: false
      # 归还连接时不检测连接有效性，提高性能
      test-on-return: false
      # 当连接池熟练大于 20 时，自动开启 prepareStatement 缓存
      max-pool-prepared-statement-per-connection-size: 20
      # 扩展插件
      filters: stat,wall
      # 记录缓存 SQL
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 缓存 prepareStatement
      pool-prepared-statements: true

#  jpa:
#    open-in-view: true

server:
  port: 8091
  servlet:
    context-path: /teamnote