spring:
  datasource:
    url: jdbc:mysql://172.16.120.83:3306/asl_station?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: asing1elife
    password: as1AliDB,

server:
  port: 8001
  servlet:
    context-path: /teamnote